{{- if .Values.pvc }}
  {{- range $name, $value := .Values.pvc }}
  {{- if $value}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "k8s-pvc.labels" $ | nindent 4 }}
  name: {{ $value.name }}
spec:
  accessModes:
  {{ toYaml $value.accessModes | indent 4 }}
  storageClassName: {{ $value.storageClassName | default "local-path" | quote }}
  resources:
    requests:
      storage: {{ $value.size | quote }}
---
{{- end }}
{{- end }}
{{- end }}